# Generated by Django 3.0.2 on 2023-01-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20230104_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='ava.jpg', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
